const assert = require("assert")
const fs = require("fs")
const path = require("path")

const root = path.resolve(__dirname, "..")
const serverSource = fs.readFileSync(path.join(root, "server.js"), "utf8")
const flowSource = fs.readFileSync(path.join(root, "src/domain/admin-assisted-ai-flow.js"), "utf8")

assert.match(serverSource, /atendimentoAssistidoIa:\s*"adm_atendimento_assistido_ia"/)
assert.match(serverSource, /title:\s*"👨‍⚖️ Atendimento Assistido por IA"/)
assert.match(serverSource, /async function processarAdminWhatsApp\(from, text, msgObj = null\)/)
assert.match(serverSource, /processarAdminWhatsApp\(from, text, msgObj\)/)
assert.match(serverSource, /iniciarAtendimentoAssistidoAdmin\(from, depsAtendimentoAssistido\)/)
assert.match(serverSource, /processarAtendimentoAssistidoAdmin\(from, text, msgObj, depsAtendimentoAssistido\)/)
assert.match(serverSource, /agendarPersistenciaSessoesAdminAssistidas/)
assert.match(serverSource, /carregarSessoesAdminAssistidasPersistidas\(sessoesAdminWhatsApp\)/)
assert.match(serverSource, /persistirSessoesAdminAssistidasAgora\(sessoesAdminWhatsApp\)/)
assert.match(serverSource, /async function finalizarCadastroAssistidoAdmin\(from, u\)/)
assert.match(serverSource, /finalizarCadastroAssistido:\s*finalizarCadastroAssistidoAdmin/)
assert.match(serverSource, /await finalizarCadastro\(telefone, u\)/)
assert.match(serverSource, /filasMensagens\.get\(from\)\.push\(\{ nomeWA, text, msgObj, resolve \}\)/)
assert.match(serverSource, /executarComLockUsuario\(\s*from,\s*\(\) => ehWhatsAppAdmin\(from\)/)
assert.doesNotMatch(serverSource, /async function processar\(from, nomeWA, text, msgObj\) \{\s*if \(ehWhatsAppAdmin\(from\)\)/)

const inicioIdx = serverSource.indexOf("iniciarAtendimentoAssistidoAdmin(from, depsAtendimentoAssistido)")
const ativoIdx = serverSource.indexOf("atendimentoAssistidoAdminAtivo(from, depsAtendimentoAssistido)")
const menuIdx = serverSource.indexOf('["", "admin", "menu", "inicio", "admin_menu", ADMIN_IDS.menu]')
assert.ok(inicioIdx > 0, "handler de inicio do atendimento assistido ausente")
assert.ok(ativoIdx > inicioIdx, "handler ativo deve ficar apos o clique de inicio")
assert.ok(menuIdx > ativoIdx, "modo assistido deve interceptar antes do menu normal")

assert.doesNotMatch(flowSource, /hsCriar|HubSpot|HUBSPOT|GROQ|OpenAI|openai|processarInterno/)
assert.match(flowSource, /deps\.finalizarCadastroAssistido/)

console.log("admin-assisted-ai-static.test.js ok")
