const assert = require("node:assert/strict")
const fs = require("node:fs")
const path = require("node:path")

const source = fs.readFileSync(path.join(__dirname, "..", "server.js"), "utf8")
const inicio = source.indexOf('if (comandoDoc === "docs_proxdoc")')
const fim = source.indexOf('if (comandoDoc === "docs_depois")', inicio)
const bloco = source.slice(inicio, fim)
assert.ok(inicio >= 0 && fim > inicio)
assert.ok(bloco.indexOf("marcarStatusDocumento") < bloco.indexOf("consolidarDocumentosDoCasoSeguro"))
assert.match(bloco, /getDocsPendentes\(u\)\.length === 0/)
assert.ok(bloco.indexOf("consolidarDocumentosDoCasoSeguro") < bloco.indexOf("telaEnvioDoc"))
const blocoDepois = source.slice(fim, source.indexOf("if (comandoDoc", fim + 30))
assert.doesNotMatch(blocoDepois, /consolidarDocumentosDoCasoSeguro/)
const inicioMidia = source.indexOf("async function processarMidia")
const fimMidia = source.indexOf("async function", inicioMidia + 30)
assert.doesNotMatch(source.slice(inicioMidia, fimMidia), /consolidarDocumentosDoCasoSeguro/)
const segura = source.slice(source.indexOf("async function consolidarDocumentosDoCasoSeguro"), inicioMidia)
assert.match(segura, /try\s*{/)
assert.match(segura, /catch\s*\(/)
assert.match(segura, /falha nao bloqueante/)
console.log("document-consolidation-server-static.test.js: ok")
