"use strict"
const test=require("node:test"),assert=require("node:assert/strict")
const {createDriveSingleCaseAdapter}=require("../src/adapters/drive-single-case-adapter")
const ROOT="root-folder",DEST={logicalId:"area-inss",name:"Area"},HASH="a".repeat(64),CTX={idempotencyKey:"key-1"}
function harness(overrides={}){const calls=[];const client={list:async q=>{calls.push(["list",q]);return[]},createFolder:async q=>{calls.push(["createFolder",q]);return{id:"folder-created"}},getById:async id=>{calls.push(["getById",id]);return null},upload:async q=>{calls.push(["upload",q]);return{id:"file-created"}},...overrides};return{calls,adapter:createDriveSingleCaseAdapter({client,rootFolderId:ROOT,timeoutMs:20})}}
for(const [name,method,args] of [["pasta de área ausente","findAreaFolders",[DEST]],["pasta do caso ausente","findCaseFolders",["area-folder",DEST]],["arquivo por hash ausente","findFilesByHash",["case-folder",HASH]]])test(name,async()=>assert.deepEqual(await harness().adapter[method](...args),[]))
for(const [name,method,args] of [["pasta de área existente","findAreaFolders",[DEST]],["pasta do caso existente","findCaseFolders",["area-folder",DEST]],["arquivo por hash existente","findFilesByHash",["case-folder",HASH]]])test(name,async()=>{const h=harness({list:async()=>[{id:"item-one"}]});assert.deepEqual(await h.adapter[method](...args),[{id:"item-one"}])})
for(const [name,method,args] of [["múltiplas pastas de área","findAreaFolders",[DEST]],["múltiplas pastas do caso","findCaseFolders",["area-folder",DEST]],["múltiplos arquivos por hash","findFilesByHash",["case-folder",HASH]]])test(name,async()=>{const h=harness({list:async()=>[{id:"item-one"},{id:"item-two"}]});assert.equal((await h.adapter[method](...args)).length,2)})
test("criação de pastas sem retry",async()=>{const h=harness();assert.deepEqual(await h.adapter.createAreaFolder({destination:DEST,context:CTX}),{id:"folder-created"});assert.deepEqual(await h.adapter.createCaseFolder({parentId:"area-folder",destination:DEST,context:CTX}),{id:"folder-created"});assert.equal(h.calls.filter(x=>x[0]==="createFolder").length,2)})
test("upload único",async()=>{const h=harness();const payload={parentId:"case-folder",bytesBase64:"eA==",sha256:HASH,size:1,document:{contentDocumentId:"doc-1"},context:CTX,idempotencyKey:"key-1"};assert.deepEqual(await h.adapter.upload(payload),{id:"file-created"});assert.equal(h.calls.filter(x=>x[0]==="upload").length,1)})
test("verificação de pasta e upload",async()=>{const h=harness({getById:async id=>id.startsWith("folder")?{id,logicalId:DEST.logicalId,name:DEST.name,parentId:ROOT,trashed:false}:{id,parentId:"case-folder",sha256:HASH,size:1,contentDocumentId:"doc-1",trashed:false}});const folder=await h.adapter.verifyFolder("folder-one");assert.equal(folder.verified,true);assert.equal(folder.parentId,"root");assert.equal((await h.adapter.verifyUpload("file-one",HASH)).verified,true)})
test("timeout de escrita é desconhecido e uma tentativa",async()=>{let attempts=0;const h=harness({upload:async()=>{attempts++;return new Promise(()=>{})}});await assert.rejects(()=>h.adapter.upload({parentId:"case-folder",bytesBase64:"eA==",sha256:HASH,size:1,document:{contentDocumentId:"doc-1"},context:CTX,idempotencyKey:"key-1"}),/DRIVE_EXTERNAL_EFFECT_UNKNOWN/);assert.equal(attempts,1)})
test("erro sanitizado e construção sem rede",async()=>{let calls=0;const h=harness({list:async()=>{calls++;throw new Error("PII secret path")}});assert.equal(calls,0);await assert.rejects(()=>h.adapter.findAreaFolders(DEST),e=>e.message==="DRIVE_EXTERNAL_ERROR");assert.equal(calls,1)})
