"use strict";const test=require("node:test"),assert=require("node:assert/strict");const{createGoogleDriveSingleCaseClient}=require("../src/adapters/google-drive-single-case-client")
function harness(pages=[{files:[]}],failure){const calls=[];class OAuth2{setCredentials(v){calls.push(["credentials",!!v.refresh_token])}}const files={list:async q=>{calls.push(["list",q]);if(failure)throw failure;return{data:pages.shift()}},get:async q=>{calls.push(["get",q]);return{data:{id:q.fileId,name:"x",parents:["root"],trashed:false,appProperties:{logicalId:"area"}}}},create:async q=>{calls.push(["create",q]);if(failure)throw failure;return{data:{id:"created-id"}}}};const google={auth:{OAuth2},drive:()=>({files})};return{calls,client:createGoogleDriveSingleCaseClient({clientId:"id",clientSecret:"secret",refreshToken:"refresh",googleModule:google,timeoutMs:20})}}
test("construção sem rede",()=>{const h=harness();assert.equal(h.calls.filter(x=>x[0]!=="credentials").length,0)})
test("paginação preserva zero um e múltiplos",async()=>{const h=harness([{files:[{id:"one"}],nextPageToken:"next"},{files:[{id:"two"}]}]);assert.deepEqual(await h.client.list({kind:"file",parentId:"parent",sha256:"a".repeat(64)}),[{id:"one"},{id:"two"}]);assert.equal(h.calls.filter(x=>x[0]==="list").length,2)})
test("request de busca é read-only",async()=>{const h=harness();await h.client.list({kind:"folder",parentId:"root",name:"Area",logicalId:"area"});assert.equal(h.calls.some(x=>x[0]==="create"),false)})
test("busca estrita por logicalId não injeta filtro de nome",async()=>{const h=harness();await h.client.list({kind:"folder",parentId:"root",logicalId:"area"});const query=h.calls.find(x=>x[0]==="list")[1].q;assert.match(query,/logicalId/);assert.doesNotMatch(query,/name =/)} )
test("timeout e erro são sanitizados",async()=>{const h=harness([],Object.assign(new Error("private timeout"),{code:"ETIMEDOUT"}));await assert.rejects(()=>h.client.list({kind:"file",parentId:"p",sha256:"a".repeat(64)}),e=>e.message==="GOOGLE_DRIVE_TIMEOUT")})
test("escrita não tem retry",async()=>{const h=harness([],new Error("private"));await assert.rejects(()=>h.client.createFolder({parentId:"root",destination:{name:"x",logicalId:"x"}}),e=>e.message==="GOOGLE_DRIVE_EXTERNAL_EFFECT_UNKNOWN");assert.equal(h.calls.filter(x=>x[0]==="create").length,1)})
test("credenciais ausentes bloqueadas",()=>assert.throws(()=>createGoogleDriveSingleCaseClient({googleModule:{}}),/GOOGLE_DRIVE_CREDENTIALS_MISSING/))
