const assert = require("node:assert/strict")
const fs = require("node:fs")
const source = fs.readFileSync(require("node:path").join(__dirname, "..", "scripts", "import-real-cases.js"), "utf8")

assert.match(source, /confirm-live-import/)
assert.match(source, /IMPORT_AUTOMATIONS_CONFIRMED_DISABLED/)
assert.match(source, /cpf_do_cliente.*phone.*email/s)
assert.match(source, /numero_de_caso/)
assert.match(source, /checkpoint\.json/)
assert.match(source, /timeout: 15000/)
assert.match(source, /allow-readonly-hubspot/)
assert.match(source, /pilotCandidates/)
assert.match(source, /area_juridica:\s*"Previdenciário \(INSS\)"/)
assert.doesNotMatch(source, /PrevidenciÃ|PrevidenciÃƒ/)
assert.match(source, /offlineByDefault.*command === "audit".*command === "review".*command === "dry-run"/)
assert.doesNotMatch(source, /console\.log\([^\n]*(cpf|phone|email|name)/i)
console.log("import-real-cases.test.js: ok")
