const assert = require("node:assert/strict")
const fs = require("node:fs")
const path = require("node:path")

const source = fs.readFileSync(path.join(__dirname, "..", "server.js"), "utf8")
const inicio = source.indexOf("async function baixarMidia")
const fim = source.indexOf("const IMAGEM_BOAS_VINDAS_URL", inicio)
const trecho = source.slice(inicio, fim)
assert.ok(inicio >= 0 && fim > inicio)
assert.match(source, /WHATSAPP_MEDIA_MAX_BYTES/)
assert.match(trecho, /info\.data\.file_size/)
assert.match(trecho, /maxContentLength:\s*WHATSAPP_MEDIA_MAX_BYTES/)
assert.match(trecho, /maxBodyLength:\s*WHATSAPP_MEDIA_MAX_BYTES/)
assert.match(trecho, /buffer\.length\s*>\s*WHATSAPP_MEDIA_MAX_BYTES/)
assert.match(trecho, /MEDIA_SIZE_LIMIT/)
assert.match(trecho, /new Error\(/)
assert.doesNotMatch(trecho, /newError\(/)
assert.doesNotMatch(trecho, /e\.message/)
console.log("media-download-security.test.js: ok")
