"use strict"

const test = require("node:test")
const assert = require("node:assert/strict")
const crypto = require("node:crypto")
const fs = require("node:fs")
const path = require("node:path")
const { newCheckpoint, createSingleCaseApplyExecutor } = require("../src/domain/single-case-apply")
const { AUTH_SCOPES, AUTHORIZATION_SCHEMA_VERSION, authorizablePlanHash, reservationEvidenceHash, authorizationPayload, createAuthorizationVerifier, canonicalize, sha256 } = require("../src/domain/single-case-apply-contracts")
const { createSingleCaseCoordinationComponents } = require("../src/composition/single-case-coordination-components")
const { LEASE_TABLE, CHECKPOINT_TABLE, FENCING_SEQUENCE, SEQUENCE_SPEC, CREATE_SCHEMA_SQL, EXPECTED_COLUMNS, REQUIRED_CHECKS, CHECK_EXPRESSIONS, CHECK_COLUMNS, mapError, createSingleCaseCoordinationRepository, validateSingleCaseCoordinationSchema, migrateSingleCaseCoordination } = require("../src/infrastructure/single-case-coordination-postgres")

const NOW = "2026-01-02T10:00:00.000Z", CASE = "fixture-case-coordination", OWNER = "fixture-worker-01"
const decision = () => ({ caseImportId:CASE, caseFingerprint:"abcdef123456", caseNumber:"PRV.260102.001", authorizablePlanHash:"a".repeat(64), authorizationIds:["fixture-auth-apply","fixture-auth-writes"] })
const checkpoint = () => newCheckpoint(decision())
const clone = value => value == null ? value : structuredClone(value)
const initializationBinding = () => ({ ...decision(), planHash:"1".repeat(64), manifestHash:"2".repeat(64), reservationEvidenceHash:"3".repeat(64), schemaVersion:AUTHORIZATION_SCHEMA_VERSION, requiredScopes:AUTH_SCOPES })
const authorizationRows = () => Object.keys(AUTH_SCOPES).map((authorization_type,index)=>({ authorization_id:decision().authorizationIds[index],authorization_type,case_import_id:CASE,case_fingerprint:decision().caseFingerprint,case_number:decision().caseNumber,authorizable_plan_hash:decision().authorizablePlanHash,plan_hash:"1".repeat(64),manifest_hash:"2".repeat(64),reservation_evidence_hash:"3".repeat(64),expires_at:"2026-01-02T11:00:00.000Z",revoked:false,consumed_at:null,consumed_by:null }))

function memoryPool({ unavailable=false, authorizationRows=[], failCheckpointInsert=false }={}) {
  const state={lease:null,checkpoint:null,authorizations:clone(authorizationRows),token:0,writes:0,commits:0,rollbacks:0,migrated:false,schema:false,failNextLeaseInsert:false,failCheckpointInsert,lockWaits:0,events:[],sequence:{schema_name:"public",sequence_name:FENCING_SEQUENCE,relkind:"S",data_type:"bigint",seqincrement:"1",seqmin:"1",seqmax:"9223372036854775807",seqstart:"1",seqcache:"1",seqcycle:false,is_owned:false}}
  const locks=new Map();let clientCounter=0
  const acquireLock=async(key,id,held)=>{if(held.has(key))return;const current=locks.get(key);if(!current){locks.set(key,{owner:id,waiters:[]});held.add(key);state.events.push(`lock:${key}:${id}`);return}state.lockWaits++;state.events.push(`wait:${key}:${id}`);await new Promise(resolve=>current.waiters.push({id,resolve}));held.add(key);state.events.push(`lock:${key}:${id}`)}
  const releaseLocks=(id,held)=>{for(const key of held){const current=locks.get(key);if(!current||current.owner!==id)continue;const next=current.waiters.shift();if(next){current.owner=next.id;queueMicrotask(next.resolve)}else locks.delete(key)}held.clear()}
  const query = async (sql, params=[]) => {
    const text=String(sql).replace(/\s+/g," ").trim()
    if(text==="BEGIN"||text==="COMMIT"||text==="ROLLBACK")return{rows:[],rowCount:0}
    if(text.startsWith("SELECT pg_advisory_xact_lock"))return{rows:[{}],rowCount:1}
    if(text.startsWith("SELECT * FROM single_case_apply_leases"))return{rows:state.lease&&state.lease.case_import_id===params[0]?[clone(state.lease)]:[],rowCount:state.lease&&state.lease.case_import_id===params[0]?1:0}
    if(text.startsWith("SELECT nextval")){state.token++;return{rows:[{fencing_token:state.token}],rowCount:1}}
    if(text.startsWith("INSERT INTO single_case_apply_leases")){if(state.failNextLeaseInsert){state.failNextLeaseInsert=false;throw new Error("DRIVER_INTERNAL_DETAIL")}const old=state.lease;state.lease={case_import_id:params[0],lease_id:params[1],fencing_token:Number(params[2]),owner_id:params[3],acquired_at:params[4],expires_at:params[5],released_at:null,version:old?old.version+1:1,created_at:old?.created_at||params[4],updated_at:params[4]};state.writes++;return{rows:[clone(state.lease)],rowCount:1}}
    if(text.startsWith("UPDATE single_case_apply_leases SET expires_at")){state.lease.expires_at=params[1];state.lease.updated_at=params[0];state.lease.version++;state.writes++;return{rows:[clone(state.lease)],rowCount:1}}
    if(text.startsWith("UPDATE single_case_apply_leases SET released_at")){state.lease.released_at=params[1];state.lease.updated_at=params[1];state.lease.version++;state.writes++;return{rows:[],rowCount:1}}
    if(text.startsWith("SELECT * FROM single_case_apply_checkpoints"))return{rows:state.checkpoint&&state.checkpoint.case_import_id===params[0]?[clone(state.checkpoint)]:[],rowCount:state.checkpoint&&state.checkpoint.case_import_id===params[0]?1:0}
    if(text.startsWith("WITH locked")){state.writes++;const matches=state.authorizations.filter(row=>params[0].includes(row.authorization_id));let status="binding_mismatch";if(!matches.length)status="not_found";else if(matches.some(x=>x.consumed_at))status="already_consumed";else if(matches.some(x=>x.revoked))status="revoked";else if(matches.some(x=>Date.parse(x.expires_at)<=Date.parse(params[1])))status="expired";else if(matches.length===2&&matches.every(x=>params[3].includes(x.authorization_type)&&x.case_import_id===params[4]&&x.case_fingerprint===params[5]&&x.case_number===params[6]&&x.authorizable_plan_hash===params[7]&&x.plan_hash===params[8]&&x.manifest_hash===params[9]&&x.reservation_evidence_hash===params[10])){status="consumed";for(const x of matches){x.consumed_at=params[1];x.consumed_by=params[2]}}return{rows:[{status}],rowCount:1}}
    if(text.startsWith("INSERT INTO single_case_apply_checkpoints")){if(state.failCheckpointInsert)throw new Error("SIMULATED_CHECKPOINT_INSERT_FAILURE");state.checkpoint={case_import_id:params[0],schema_version:params[1],checkpoint_version:params[2],authorizable_plan_hash:params[3],case_number:params[4],case_fingerprint:params[5],authorization_ids:JSON.parse(params[6]),global_status:params[7],checkpoint_payload:JSON.parse(params[8]),fencing_token:params[9],lease_id:params[10],created_at:state.checkpoint?.created_at||params[11],updated_at:params[11],authorization_consumed_by:params.length>12?params[12]:(state.checkpoint?.authorization_consumed_by||null)};state.writes++;return{rows:[],rowCount:1}}
    if(text.includes("to_regclass('oraculum_state_migrations')"))return{rows:[{table_name:"oraculum_state_migrations"}],rowCount:1}
    if(text.startsWith("SELECT migration_id"))return{rows:state.migrated?[{migration_id:"single-case-apply-coordination-v1"}]:[],rowCount:state.migrated?1:0}
    if(text.startsWith("CREATE SEQUENCE")){state.schema=true;return{rows:[],rowCount:0}}
    if(text.startsWith("ALTER TABLE single_case_apply_checkpoints ADD COLUMN")){state.schema=true;return{rows:[],rowCount:0}}
    if(text.includes("information_schema.columns")){const rows=(EXPECTED_COLUMNS[params[0]]||[]).map((item,index)=>({column_name:item.name,data_type:item.type,udt_name:item.udt,is_nullable:item.nullable?"YES":"NO",column_default:item.defaultValue,ordinal_position:index+1}));return{rows:state.schema?rows:[],rowCount:state.schema?rows.length:0}}
    if(text.includes("FROM pg_constraint")){const rows=[{conname:`${params[0]}_pkey`,contype:"p",columns:["case_import_id"]},...(params[0]===LEASE_TABLE?[{conname:"single_case_lease_id_unique",contype:"u",columns:["lease_id"]},{conname:"single_case_lease_token_unique",contype:"u",columns:["fencing_token"]}]:[]),...(REQUIRED_CHECKS[params[0]]||[]).map(conname=>({conname,contype:"c",definition:`CHECK (${CHECK_EXPRESSIONS[conname]})`,columns:CHECK_COLUMNS[conname]}))];return{rows:state.schema?rows:[],rowCount:state.schema?rows.length:0}}
    if(text.includes("FROM pg_index")){const rows=state.schema?[{index_name:"single_case_lease_expiry_idx",is_unique:false,method:"btree",key_attribute_count:1,total_attribute_count:1,has_expressions:false,predicate:"released_at IS NULL",key_columns:["expires_at"]}]:[];return{rows,rowCount:rows.length}}
    if(text.includes("JOIN pg_sequence")){const rows=state.schema?[clone(state.sequence)]:[];return{rows,rowCount:rows.length}}
    if(text.startsWith("INSERT INTO oraculum_state_migrations")){state.migrated=true;state.writes++;return{rows:[],rowCount:1}}
    throw new Error(`UNEXPECTED_SQL:${text.slice(0,80)}`)
  }
  const pool={state,query:async(...args)=>{if(unavailable)throw new Error("POOL_UNAVAILABLE");return query(...args)},connect:async()=>{if(unavailable)throw new Error("POOL_UNAVAILABLE");const id=++clientCounter,held=new Set(),undo={};let finished=false;return{query:async(sql,p=[])=>{const t=String(sql).replace(/\s+/g," ").trim();if(t.startsWith("SELECT pg_advisory_xact_lock"))await acquireLock(`advisory:${p[0]}`,id,held);if(t.startsWith("SELECT * FROM single_case_apply_leases")&&t.endsWith("FOR UPDATE"))await acquireLock(`lease:${p[0]}`,id,held);if(t.startsWith("SELECT * FROM single_case_apply_checkpoints")&&t.endsWith("FOR UPDATE"))await acquireLock(`checkpoint:${p[0]}`,id,held);if((t.startsWith("INSERT INTO single_case_apply_leases")||t.startsWith("UPDATE single_case_apply_leases"))&&!("lease" in undo))undo.lease=clone(state.lease);if(t.startsWith("WITH locked")&&!("authorizations" in undo))undo.authorizations=clone(state.authorizations);if(t.startsWith("INSERT INTO single_case_apply_checkpoints")&&!("checkpoint" in undo))undo.checkpoint=clone(state.checkpoint);if((t.startsWith("CREATE SEQUENCE")||t.startsWith("ALTER TABLE"))&&!("schema" in undo)){undo.schema=state.schema;undo.migrated=state.migrated;undo.writes=state.writes}if(t==="COMMIT"){state.commits++;finished=true;releaseLocks(id,held);return{rows:[],rowCount:0}}if(t==="ROLLBACK"){if("lease" in undo)state.lease=undo.lease;if("authorizations" in undo)state.authorizations=undo.authorizations;if("checkpoint" in undo)state.checkpoint=undo.checkpoint;if("schema" in undo){state.schema=undo.schema;state.migrated=undo.migrated;state.writes=undo.writes}state.rollbacks++;finished=true;releaseLocks(id,held);return{rows:[],rowCount:0}}return query(sql,p)},release(){if(!finished)releaseLocks(id,held)}}}}
  return pool
}
const repo = (pool=memoryPool(), options={}) => {const clock=options.clock||{value:NOW};return{pool,clock,repository:createSingleCaseCoordinationRepository({pool,ownerId:options.ownerId||OWNER,now:()=>clock.value,leaseDurationMs:options.leaseDurationMs||60000})}}
const acquire = repository => repository.acquireLease({caseImportId:CASE,owner:OWNER})

test("aquisição inicial cria lease exclusivo",async()=>{const {repository}=repo();const lease=await acquire(repository);assert.equal(lease.fencingToken,1);assert.equal(lease.caseImportId,CASE)})
test("duas aquisições simultâneas realmente intercalam e somente uma vence",async()=>{const {pool,repository}=repo();const results=await Promise.allSettled([acquire(repository),acquire(repository)]);assert.equal(results.filter(x=>x.status==="fulfilled").length,1);assert.match(results.find(x=>x.status==="rejected").reason.message,/LEASE_ALREADY_HELD/);assert(pool.state.lockWaits>0);assert.equal(pool.state.lease.released_at,null)})
test("lease vigente bloqueia segundo proprietário",async()=>{const {repository}=repo();await acquire(repository);await assert.rejects(()=>repository.acquireLease({caseImportId:CASE,owner:OWNER,now:NOW}),/LEASE_ALREADY_HELD/)})
test("expiração permite nova aquisição e token monotônico",async()=>{const {repository,clock}=repo();const a=await acquire(repository);clock.value="2026-01-02T10:01:00.001Z";const b=await repository.acquireLease({caseImportId:CASE,owner:OWNER});assert(b.fencingToken>a.fencingToken);assert.notEqual(a.leaseId,b.leaseId)})
test("renovação estende lease",async()=>{const {repository,clock}=repo(),lease=await acquire(repository);clock.value="2026-01-02T10:00:30.000Z";const renewed=await repository.renewLease(lease);assert(Date.parse(renewed.expiresAt)>Date.parse(lease.expiresAt))})
test("renovação após expiração falha",async()=>{const {repository,clock}=repo(),lease=await acquire(repository);clock.value="2026-01-02T10:01:00.001Z";await assert.rejects(()=>repository.renewLease(lease),/LEASE_EXPIRED/)})
test("request.now retroativo não ressuscita lease",async()=>{const {repository,clock}=repo(),lease=await acquire(repository);clock.value="2026-01-02T10:02:00.000Z";await assert.rejects(()=>repository.renewLease({...lease,now:"2026-01-02T09:00:00.000Z"}),/LEASE_EXPIRED/)})
test("request.now futuro não força expiração",async()=>{const {repository,clock}=repo(),lease=await acquire(repository);clock.value="2026-01-02T10:00:30.000Z";const renewed=await repository.renewLease({...lease,now:"2099-01-01T00:00:00.000Z"});assert(Date.parse(renewed.expiresAt)>Date.parse(lease.expiresAt))})
test("renovação que não avança prazo é recusada",async()=>{const {repository}=repo(),lease=await acquire(repository);await assert.rejects(()=>repository.renewLease(lease),/LEASE_EXPIRED/)})
test("liberação é idempotente para o mesmo lease",async()=>{const {repository}=repo(),lease=await acquire(repository);assert.deepEqual(await repository.releaseLease(lease),{released:true});assert.deepEqual(await repository.releaseLease(lease),{released:true})})
test("lease divergente falha fechado",async()=>{const {repository}=repo(),lease=await acquire(repository);await assert.rejects(()=>repository.releaseLease({...lease,leaseId:"lease-fixture-other"}),/LEASE_NOT_FOUND/)})
test("proprietário divergente é recusado",async()=>{const {repository}=repo();await assert.rejects(()=>repository.acquireLease({caseImportId:CASE,owner:"fixture-other",now:NOW}),/LEASE_OWNER_MISMATCH/)})
test("token antigo é recusado",async()=>{const {repository,clock}=repo(),first=await acquire(repository);clock.value="2026-01-02T10:01:00.001Z";await repository.acquireLease({caseImportId:CASE,owner:OWNER});await assert.rejects(()=>repository.renewLease(first),/(LEASE_NOT_FOUND|FENCING_REJECTED)/)})
test("token consumido antes de rollback não é reutilizado",async()=>{const pool=memoryPool(),{repository}=repo(pool);pool.state.failNextLeaseInsert=true;await assert.rejects(()=>acquire(repository),/POSTGRES_TRANSACTION_FAILED/);const lease=await acquire(repository);assert.equal(lease.fencingToken,2);assert.equal(pool.state.rollbacks,1)})
test("liberações concorrentes intercalam e são idempotentes",async()=>{const {pool,repository}=repo(),lease=await acquire(repository),before=pool.state.lockWaits,results=await Promise.all([repository.releaseLease(lease),repository.releaseLease(lease)]);assert.deepEqual(results,[{released:true},{released:true}]);assert(pool.state.lockWaits>before)})
test("resposta incompleta do banco falha sanitizada",async()=>{const pool=memoryPool(),{repository}=repo(pool);pool.state.lease={case_import_id:CASE,lease_id:"bad"};await assert.rejects(()=>repository.acquireLease({caseImportId:CASE,owner:OWNER,now:"2026-01-03T10:00:00.000Z"}),/POSTGRES_TRANSACTION_FAILED/)})
test("indisponibilidade é sanitizada",async()=>{const {repository}=repo(memoryPool({unavailable:true}));await assert.rejects(()=>acquire(repository),/POSTGRES_UNAVAILABLE/)})

test("checkpoint ausente retorna null sem escrita",async()=>{const {pool,repository}=repo();assert.equal(await repository.loadCheckpoint(CASE),null);assert.equal(pool.state.writes,0)})
test("inicialização confirma consumo e checkpoint pending na mesma transação",async()=>{const pool=memoryPool({authorizationRows:authorizationRows()}),{repository}=repo(pool),lease=await acquire(repository),result=await repository.initializeCheckpoint({...lease,checkpoint:checkpoint(),authorization:initializationBinding()});assert.deepEqual(result,{saved:true,version:1,authorizationConsumedBy:`executor:${lease.leaseId}`});assert.equal(pool.state.commits,2);assert.equal(pool.state.checkpoint.checkpoint_version,1);assert.equal(pool.state.checkpoint.global_status,"pending");assert.equal(pool.state.checkpoint.authorization_consumed_by,`executor:${lease.leaseId}`);assert(pool.state.authorizations.every(row=>row.consumed_by===`executor:${lease.leaseId}`))})
test("falha antes do commit reverte consumo e não cria checkpoint",async()=>{const pool=memoryPool({authorizationRows:authorizationRows(),failCheckpointInsert:true}),{repository}=repo(pool),lease=await acquire(repository);await assert.rejects(()=>repository.initializeCheckpoint({...lease,checkpoint:checkpoint(),authorization:initializationBinding()}),/POSTGRES_TRANSACTION_FAILED/);assert.equal(pool.state.checkpoint,null);assert(pool.state.authorizations.every(row=>row.consumed_at===null&&row.consumed_by===null));assert.equal(pool.state.rollbacks,1)})
test("novo lease avança checkpoint e preserva proveniência imutável",async()=>{const pool=memoryPool({authorizationRows:authorizationRows()}),clock={value:NOW},{repository}=repo(pool,{clock}),first=await acquire(repository);await repository.initializeCheckpoint({...first,checkpoint:checkpoint(),authorization:initializationBinding()});const provenance=pool.state.checkpoint.authorization_consumed_by;clock.value="2026-01-02T10:01:00.001Z";const second=await repository.acquireLease({caseImportId:CASE,owner:OWNER}),loaded=structuredClone(await repository.loadCheckpoint(CASE));loaded.status="running";loaded.steps.reservation.status="running";const saved=await repository.compareAndSetCheckpoint({...second,expectedVersion:1,checkpoint:loaded});assert.equal(saved.version,2);assert.equal(pool.state.checkpoint.lease_id,second.leaseId);assert.equal(Number(pool.state.checkpoint.fencing_token),second.fencingToken);assert.equal(pool.state.checkpoint.authorization_consumed_by,provenance)})
test("CAS versão zero cria versão um",async()=>{const {repository}=repo(),lease=await acquire(repository),cp=checkpoint(),saved=await repository.compareAndSetCheckpoint({...lease,expectedVersion:0,checkpoint:cp,now:NOW});assert.deepEqual(saved,{saved:true,version:1});assert.equal((await repository.loadCheckpoint(CASE)).version,1)})
test("owner divergente não cria checkpoint por CAS",async()=>{const pool=memoryPool(),clock={value:NOW},{repository}=repo(pool,{clock}),lease=await acquire(repository),other=repo(pool,{clock,ownerId:"fixture-worker-other"}).repository;await assert.rejects(()=>other.compareAndSetCheckpoint({...lease,expectedVersion:0,checkpoint:checkpoint()}),error=>error.message==="LEASE_OWNER_MISMATCH");assert.equal(pool.state.checkpoint,null)})
test("owner divergente não altera checkpoint existente",async()=>{const pool=memoryPool(),clock={value:NOW},{repository}=repo(pool,{clock}),lease=await acquire(repository);await repository.compareAndSetCheckpoint({...lease,expectedVersion:0,checkpoint:checkpoint()});const before=clone(pool.state.checkpoint),other=repo(pool,{clock,ownerId:"fixture-worker-other"}).repository,loaded=structuredClone(await repository.loadCheckpoint(CASE));await assert.rejects(()=>other.compareAndSetCheckpoint({...lease,expectedVersion:1,checkpoint:loaded}),error=>error.message==="LEASE_OWNER_MISMATCH");assert.deepEqual(pool.state.checkpoint,before);assert.equal(pool.state.checkpoint.checkpoint_version,1)})
test("CAS atualiza versão exatamente em um",async()=>{const {repository}=repo(),lease=await acquire(repository),cp=checkpoint();await repository.compareAndSetCheckpoint({...lease,expectedVersion:0,checkpoint:cp,now:NOW});const loaded=structuredClone(await repository.loadCheckpoint(CASE)),saved=await repository.compareAndSetCheckpoint({...lease,expectedVersion:1,checkpoint:loaded,now:NOW});assert.equal(saved.version,2);assert.equal((await repository.loadCheckpoint(CASE)).version,2)})
test("conflito de versão não sobrescreve",async()=>{const {repository}=repo(),lease=await acquire(repository),cp=checkpoint();await repository.compareAndSetCheckpoint({...lease,expectedVersion:0,checkpoint:cp,now:NOW});await assert.rejects(()=>repository.compareAndSetCheckpoint({...lease,expectedVersion:0,checkpoint:cp,now:NOW}),/CAS_CONFLICT/)})
test("CAS concorrente realmente intercala, incrementa uma vez e preserva vencedor",async()=>{const {pool,repository}=repo(),lease=await acquire(repository),cp=checkpoint(),before=pool.state.lockWaits,results=await Promise.allSettled([repository.compareAndSetCheckpoint({...lease,expectedVersion:0,checkpoint:cp}),repository.compareAndSetCheckpoint({...lease,expectedVersion:0,checkpoint:cp})]);assert.equal(results.filter(x=>x.status==="fulfilled").length,1);assert.equal(results.find(x=>x.status==="rejected").reason.message,"CAS_CONFLICT");assert(pool.state.lockWaits>before);assert.equal(pool.state.checkpoint.checkpoint_version,1)})
test("fencing antigo não grava checkpoint",async()=>{const {repository,clock}=repo(),old=await acquire(repository);clock.value="2026-01-02T10:01:00.001Z";await repository.acquireLease({caseImportId:CASE,owner:OWNER});await assert.rejects(()=>repository.compareAndSetCheckpoint({...old,expectedVersion:0,checkpoint:checkpoint()}),/(LEASE_NOT_FOUND|FENCING_REJECTED)/)})
test("lease expirado não grava checkpoint",async()=>{const {repository,clock}=repo(),lease=await acquire(repository);clock.value="2026-01-02T10:01:00.001Z";await assert.rejects(()=>repository.compareAndSetCheckpoint({...lease,expectedVersion:0,checkpoint:checkpoint()}),/LEASE_EXPIRED/)})
test("vínculo divergente é recusado",async()=>{const {repository}=repo(),lease=await acquire(repository),cp=checkpoint();cp.caseImportId="fixture-case-other";await assert.rejects(()=>repository.compareAndSetCheckpoint({...lease,expectedVersion:0,checkpoint:cp,now:NOW}),/CHECKPOINT_BINDING_MISMATCH/)})
test("vínculo persistido não pode ser trocado em CAS posterior",async()=>{const {repository}=repo(),lease=await acquire(repository),cp=checkpoint();await repository.compareAndSetCheckpoint({...lease,expectedVersion:0,checkpoint:cp,now:NOW});const changed=structuredClone(await repository.loadCheckpoint(CASE));changed.caseFingerprint="123456abcdef";await assert.rejects(()=>repository.compareAndSetCheckpoint({...lease,expectedVersion:1,checkpoint:changed,now:NOW}),/CHECKPOINT_BINDING_MISMATCH/)})
test("checkpoint inválido e campo extra falham",async()=>{const {repository}=repo(),lease=await acquire(repository),cp=checkpoint();cp.extra=true;await assert.rejects(()=>repository.compareAndSetCheckpoint({...lease,expectedVersion:0,checkpoint:cp,now:NOW}),/INVALID_CHECKPOINT/)})
test("leitura retorna objeto profundamente imutável",async()=>{const {repository}=repo(),lease=await acquire(repository);await repository.compareAndSetCheckpoint({...lease,expectedVersion:0,checkpoint:checkpoint(),now:NOW});const cp=await repository.loadCheckpoint(CASE);assert(Object.isFrozen(cp));assert(Object.isFrozen(cp.steps));assert.throws(()=>{cp.status="failed"})})
test("leitura não altera timestamps nem estado",async()=>{const {pool,repository}=repo(),lease=await acquire(repository);await repository.compareAndSetCheckpoint({...lease,expectedVersion:0,checkpoint:checkpoint(),now:NOW});const before=clone(pool.state.checkpoint),writes=pool.state.writes;await repository.loadCheckpoint(CASE);assert.deepEqual(pool.state.checkpoint,before);assert.equal(pool.state.writes,writes)})
test("checkpoint adulterado bloqueia retomada",async()=>{const {pool,repository}=repo(),lease=await acquire(repository);await repository.compareAndSetCheckpoint({...lease,expectedVersion:0,checkpoint:checkpoint(),now:NOW});pool.state.checkpoint.checkpoint_payload.extra=true;await assert.rejects(()=>repository.loadCheckpoint(CASE),/INVALID_CHECKPOINT/)})
test("retomada após expiração preserva checkpoint e eleva token",async()=>{const {repository,clock}=repo(),first=await acquire(repository);await repository.compareAndSetCheckpoint({...first,expectedVersion:0,checkpoint:checkpoint()});clock.value="2026-01-02T10:01:00.001Z";const second=await repository.acquireLease({caseImportId:CASE,owner:OWNER});assert(second.fencingToken>first.fencingToken);assert.equal((await repository.loadCheckpoint(CASE)).version,1)})

function persistentExecutorSystem({crashAfterContact=false,reservationGate=null}={}) {
  const plan=JSON.parse(fs.readFileSync(path.join(__dirname,"fixtures","single-case-apply-plan.json"),"utf8")),keys=crypto.generateKeyPairSync("ed25519"),issuer="fixture-persistent-authority",hash=authorizablePlanHash(plan),planHash="3".repeat(64),manifestHash="4".repeat(64),evidence={verified:true,caseImportId:plan.caseImportId,caseNumber:plan.dealPlan.caseNumber,evidenceId:"fixture-reservation-proof"}
  const records=Object.entries(AUTH_SCOPES).map(([type,scope],index)=>{const record={authorizationId:`fixture-persistent-auth-${index+1}`,schemaVersion:AUTHORIZATION_SCHEMA_VERSION,type,caseImportId:plan.caseImportId,caseFingerprint:plan.caseFingerprint,caseNumber:plan.dealPlan.caseNumber,authorizablePlanHash:hash,planHash,manifestHash,reservationEvidenceHash:reservationEvidenceHash(evidence),scope:[...scope],issuer,issuedAt:"2026-07-15T11:45:00.000Z",expiresAt:"2026-07-15T12:15:00.000Z",revoked:false};return{...record,proof:crypto.sign(null,Buffer.from(authorizationPayload(record)),keys.privateKey).toString("base64")}})
  let tick=Date.parse("2026-07-15T12:00:00.000Z");const clock=()=>new Date(tick+=10).toISOString(),pool=memoryPool({authorizationRows:records.map(r=>({authorization_id:r.authorizationId,authorization_type:r.type,case_import_id:r.caseImportId,case_fingerprint:r.caseFingerprint,case_number:r.caseNumber,authorizable_plan_hash:r.authorizablePlanHash,plan_hash:r.planHash,manifest_hash:r.manifestHash,reservation_evidence_hash:r.reservationEvidenceHash,expires_at:r.expiresAt,revoked:r.revoked,consumed_at:null,consumed_by:null}))}),coordination=createSingleCaseCoordinationRepository({pool,ownerId:"fixture-executor",now:clock,leaseDurationMs:60000}),state={contacts:[],deals:[],associations:[],areas:[],folders:[],files:new Map(),crashed:false},id=(prefix,size)=>`${prefix}-${size+1}`
  const verifyContext=context=>{const preflight=context?.idempotencyKey===`${plan.caseImportId}:reservation-preflight`;if(!context||context.caseImportId!==plan.caseImportId||!Number.isInteger(context.fencingToken)||(!preflight&&canonicalize(context.authorizationIds)!==canonicalize(records.map(x=>x.authorizationId).sort()))||(preflight&&context.authorizationIds.length))throw new Error("FENCING_REJECTED")}
  const adapters={
    plans:{loadByCaseImportId:async()=>structuredClone(plan)},authorizations:{loadForCase:async()=>structuredClone(records),loadForCheckpoint:async({authorizationIds})=>{const provenance=pool.state.checkpoint?.authorization_consumed_by,rows=pool.state.authorizations.filter(row=>authorizationIds.includes(row.authorization_id));if(!provenance||rows.length!==2||rows.some(row=>row.consumed_by!==provenance))throw new Error("AUTHORIZATION_CONSUMPTION_PROVENANCE_MISMATCH");return structuredClone(records.filter(record=>authorizationIds.includes(record.authorizationId)))},consumeAuthorizations:async()=>({status:"consumed"})},coordination:{...coordination,compareAndSetCheckpoint:async request=>{if(crashAfterContact&&!state.crashed&&request.checkpoint.steps.contact.status==="completed"){state.crashed=true;throw new Error("SIMULATED_CRASH_AFTER_CONTACT_EFFECT")}return coordination.compareAndSetCheckpoint(request)}},
    reservation:{verify:async(caseImportId,caseNumber,context)=>{verifyContext(context);if(reservationGate)await reservationGate;return{verified:true,caseImportId,caseNumber,evidenceId:"fixture-reservation-proof"}}},
    contacts:{findContactsByCpf:async cpf=>state.contacts.filter(x=>x.properties.cpf_do_cliente===cpf),findContactsByPhone:async phone=>state.contacts.filter(x=>x.properties.phone===phone),create:async({properties,context})=>{verifyContext(context);const item={id:id("contact",state.contacts.length),properties:structuredClone(properties),caseImportId:plan.caseImportId};state.contacts.push(item);return{id:item.id}},verify:async contactId=>{const x=state.contacts.find(i=>i.id===contactId);return x?{verified:true,id:x.id,cpf:x.properties.cpf_do_cliente,phone:x.properties.phone,fieldsHash:sha256(canonicalize(x.properties)),caseImportId:x.caseImportId}:null}},
    deals:{findByCaseNumber:async number=>state.deals.filter(x=>x.properties.numero_de_caso===number),create:async({properties,context})=>{verifyContext(context);const item={id:id("deal",state.deals.length),properties:structuredClone(properties)};state.deals.push(item);return{id:item.id}},verify:async dealId=>{const x=state.deals.find(i=>i.id===dealId);return x?{verified:true,id:x.id,caseNumber:x.properties.numero_de_caso,pipeline:x.properties.pipeline,stage:x.properties.dealstage,fieldsHash:sha256(canonicalize(x.properties))}:null}},
    associations:{find:async(contactId,dealId)=>state.associations.filter(x=>x.contactId===contactId&&x.dealId===dealId),create:async({contactId,dealId,type,context})=>{verifyContext(context);const item={id:id("association",state.associations.length),contactId,dealId,type};state.associations.push(item);return{id:item.id}},verify:async associationId=>{const x=state.associations.find(i=>i.id===associationId);return x?{verified:true,id:x.id,contactId:x.contactId,dealId:x.dealId,relation:x.type}:null}},
    drive:{findAreaFolders:async destination=>state.areas.filter(x=>x.logicalId===destination.logicalId&&x.name===destination.name),createAreaFolder:async({destination,context})=>{verifyContext(context);const x={id:id("area",state.areas.length),...structuredClone(destination),parentId:"root",trashed:false};state.areas.push(x);return{id:x.id}},findCaseFolders:async(parentId,destination)=>state.folders.filter(x=>x.parentId===parentId&&x.logicalId===destination.logicalId&&x.name===destination.name),createCaseFolder:async({parentId,destination,context})=>{verifyContext(context);const x={id:id("folder",state.folders.length),...structuredClone(destination),parentId,trashed:false};state.folders.push(x);return{id:x.id}},verifyFolder:async folderId=>{const x=[...state.areas,...state.folders].find(i=>i.id===folderId);return x?{verified:true,id:x.id,parentId:x.parentId,logicalId:x.logicalId,name:x.name,trashed:false}:null},findFilesByHash:async(parentId,hash)=>[...state.files.values()].filter(x=>x.parentId===parentId&&x.sha256===hash),upload:async({parentId,bytesBase64,sha256:expected,size,document,context})=>{verifyContext(context);const bytes=Buffer.from(bytesBase64,"base64");if(bytes.length!==size||sha256(bytes)!==expected)throw new Error("UPLOAD_INVALID");const x={id:id("file",state.files.size),parentId,sha256:expected,size,contentDocumentId:document.contentDocumentId,bytes};state.files.set(`${parentId}:${expected}`,x);return{id:x.id}},verifyUpload:async(fileId)=>{const x=[...state.files.values()].find(i=>i.id===fileId);return x?{verified:true,id:x.id,sha256:x.sha256,size:x.size,parentId:x.parentId,contentDocumentId:x.contentDocumentId}:null}},
    content:{loadBytes:async contentDocumentId=>{const number=Number(contentDocumentId.slice(1));return Buffer.from(`fixture-content-${String(number===0?12:number).padStart(2,"0")}`)}}
  }
  const executor=createSingleCaseApplyExecutor({authorizationVerifier:createAuthorizationVerifier({trustedIssuers:{[issuer]:keys.publicKey}})});return{plan,pool,state,coordination,run:()=>executor({caseImportId:plan.caseImportId,planHash,manifestHash,adapters,now:clock})}
}
test("integração persistente executa caso completo e checkpoint final",async()=>{const system=persistentExecutorSystem(),result=await system.run(),stored=await system.coordination.loadCheckpoint(system.plan.caseImportId);assert.equal(result.completed,true);assert.equal(stored.status,"completed");assert.equal(system.state.files.size,11)})
test("integração persistente retoma queda após efeito sem duplicar",async()=>{const system=persistentExecutorSystem({crashAfterContact:true});await assert.rejects(()=>system.run(),/SIMULATED_CRASH_AFTER_CONTACT_EFFECT/);assert.equal(system.state.contacts.length,1);const result=await system.run();assert.equal(result.completed,true);assert.equal(system.state.contacts.length,1);assert.equal((await system.coordination.loadCheckpoint(system.plan.caseImportId)).status,"completed")})
test("integração persistente bloqueia segunda execução concorrente",async()=>{let release;const gate=new Promise(resolve=>{release=resolve}),system=persistentExecutorSystem({reservationGate:gate}),first=system.run();while(!system.pool.state.lease||system.pool.state.lease.released_at)await new Promise(resolve=>setImmediate(resolve));await assert.rejects(()=>system.run(),/LEASE_ALREADY_HELD/);release();assert.equal((await first).completed,true)})

test("schema integral correto é aceito",async()=>{const pool=memoryPool();pool.state.schema=true;assert.deepEqual(await validateSingleCaseCoordinationSchema(pool),{ok:true,codes:[]})})
test("tipo divergente é detectado",async()=>{const pool=memoryPool();pool.state.schema=true;const base=pool.query;pool.query=async(sql,p)=>{const result=await base(sql,p);if(String(sql).includes("information_schema")&&p[0]===LEASE_TABLE)result.rows[0].data_type="integer";return result};assert.equal((await validateSingleCaseCoordinationSchema(pool)).ok,false)})
test("udt_name divergente é detectado",async()=>{const pool=memoryPool();pool.state.schema=true;const base=pool.query;pool.query=async(sql,p)=>{const result=await base(sql,p);if(String(sql).includes("information_schema"))result.rows[0].udt_name="int4";return result};assert.equal((await validateSingleCaseCoordinationSchema(pool)).ok,false)})
test("default divergente é detectado",async()=>{const pool=memoryPool();pool.state.schema=true;const base=pool.query;pool.query=async(sql,p)=>{const result=await base(sql,p);if(String(sql).includes("information_schema"))result.rows[0].column_default="'unsafe'::text";return result};assert((await validateSingleCaseCoordinationSchema(pool)).codes.some(x=>x.includes("DEFAULT_MISMATCH")))})
test("constraint extra é detectada",async()=>{const pool=memoryPool();pool.state.schema=true;const base=pool.query;pool.query=async(sql,p)=>{const result=await base(sql,p);if(String(sql).includes("FROM pg_constraint"))result.rows.push({conname:"unexpected_constraint",contype:"c",definition:"CHECK (version > 0)",columns:["version"]});return result};assert((await validateSingleCaseCoordinationSchema(pool)).codes.some(x=>x.includes("UNEXPECTED_CONSTRAINT")))})
test("coluna extra e ausente são detectadas",async()=>{for(const change of [rows=>rows.push({...rows[0],column_name:"extra",ordinal_position:rows.length+1}),rows=>rows.pop()]){const pool=memoryPool();pool.state.schema=true;const base=pool.query;pool.query=async(sql,p)=>{const result=await base(sql,p);if(String(sql).includes("information_schema"))change(result.rows);return result};assert((await validateSingleCaseCoordinationSchema(pool)).codes.some(x=>x.includes("COLUMN_")))}})
test("CHECK permissivo é detectado semanticamente",async()=>{const pool=memoryPool();pool.state.schema=true;const base=pool.query;pool.query=async(sql,p)=>{const result=await base(sql,p);if(String(sql).includes("FROM pg_constraint")&&p[0]===LEASE_TABLE)result.rows.find(x=>x.conname==="single_case_lease_token_check").definition="CHECK (fencing_token >= 0)";return result};assert((await validateSingleCaseCoordinationSchema(pool)).codes.some(x=>x.includes("CHECK_MISMATCH")))})
test("índice com predicado divergente é detectado",async()=>{const pool=memoryPool();pool.state.schema=true;const base=pool.query;pool.query=async(sql,p)=>{const result=await base(sql,p);if(String(sql).includes("FROM pg_index"))result.rows[0].predicate="released_at IS NULL OR expires_at IS NULL";return result};assert((await validateSingleCaseCoordinationSchema(pool)).codes.includes("LEASE_EXPIRY_INDEX_MISMATCH"))})

// Regression tests for array normalization and parsing formats
test("array JavaScript válido é aceito",async()=>{const pool=memoryPool();pool.state.schema=true;assert.equal((await validateSingleCaseCoordinationSchema(pool)).ok,true)})

test("string JSON válida representando array é aceita",async()=>{const pool=memoryPool();pool.state.schema=true;const base=pool.query;pool.query=async(sql,p)=>{const result=await base(sql,p);if(String(sql).includes("FROM pg_constraint"))result.rows=result.rows.map(r=>({...r,columns:JSON.stringify(r.columns)}));return result};assert.equal((await validateSingleCaseCoordinationSchema(pool)).ok,true)})

test("literal PostgreSQL '{...}' é rejeitado",async()=>{const pool=memoryPool();pool.state.schema=true;const base=pool.query;pool.query=async(sql,p)=>{const result=await base(sql,p);if(String(sql).includes("FROM pg_constraint")&&p[0]===CHECKPOINT_TABLE)result.rows=result.rows.map(r=>({...r,columns:'{case_import_id}'}));return result};const res=await validateSingleCaseCoordinationSchema(pool);assert.equal(res.ok,false);assert(res.codes.some(c=>c.includes("CHECK_MISMATCH")))})

test("objeto não-array é rejeitado",async()=>{const pool=memoryPool();pool.state.schema=true;const base=pool.query;pool.query=async(sql,p)=>{const result=await base(sql,p);if(String(sql).includes("FROM pg_constraint")&&p[0]===CHECKPOINT_TABLE)result.rows=result.rows.map(r=>({...r,columns:{a:'case_import_id'}}));return result};const res=await validateSingleCaseCoordinationSchema(pool);assert.equal(res.ok,false);assert(res.codes.some(c=>c.includes("CHECK_MISMATCH")))})

test("elemento não-string é rejeitado",async()=>{const pool=memoryPool();pool.state.schema=true;const base=pool.query;pool.query=async(sql,p)=>{const result=await base(sql,p);if(String(sql).includes("FROM pg_constraint")&&p[0]===CHECKPOINT_TABLE)result.rows=result.rows.map(r=>({...r,columns:JSON.stringify([1,2])}));return result};const res=await validateSingleCaseCoordinationSchema(pool);assert.equal(res.ok,false);assert(res.codes.some(c=>c.includes("CHECK_MISMATCH")))})

test("string vazia elemento é rejeitada",async()=>{const pool=memoryPool();pool.state.schema=true;const base=pool.query;pool.query=async(sql,p)=>{const result=await base(sql,p);if(String(sql).includes("FROM pg_constraint")&&p[0]===CHECKPOINT_TABLE)result.rows=result.rows.map(r=>({...r,columns:JSON.stringify([""])}));return result};const res=await validateSingleCaseCoordinationSchema(pool);assert.equal(res.ok,false);assert(res.codes.some(c=>c.includes("CHECK_MISMATCH")))})

test("null obrigatório é rejeitado",async()=>{const pool=memoryPool();pool.state.schema=true;const base=pool.query;pool.query=async(sql,p)=>{const result=await base(sql,p);if(String(sql).includes("FROM pg_constraint")&&p[0]===CHECKPOINT_TABLE)result.rows=result.rows.map(r=>({...r,columns:JSON.stringify(null)}));return result};const res=await validateSingleCaseCoordinationSchema(pool);assert.equal(res.ok,false);assert(res.codes.some(c=>c.includes("CHECK_MISMATCH")))})

// Primary key and unique constraint tests
test("PK errada é rejeitada",async()=>{const pool=memoryPool();pool.state.schema=true;const base=pool.query;pool.query=async(sql,p)=>{const result=await base(sql,p);if(String(sql).includes("FROM pg_constraint")&&p[0]===CHECKPOINT_TABLE){result.rows=result.rows.map(r=>r.contype==='p'?{...r,columns:JSON.stringify(["wrong_pk"])}:r)}return result};const res=await validateSingleCaseCoordinationSchema(pool);assert.equal(res.ok,false);assert(res.codes.some(c=>c.includes("PRIMARY_KEY_MISMATCH")))})

test("unique constraint com colunas erradas é rejeitada",async()=>{const pool=memoryPool();pool.state.schema=true;const base=pool.query;pool.query=async(sql,p)=>{const result=await base(sql,p);if(String(sql).includes("FROM pg_constraint")&&p[0]===LEASE_TABLE){result.rows=result.rows.map(r=>r.contype==='u'?{...r,columns:JSON.stringify(["wrong_col"])}:r)}return result};const res=await validateSingleCaseCoordinationSchema(pool);assert.equal(res.ok,false);assert(res.codes.some(c=>c.includes("UNIQUE_MISMATCH")))})

test("unique constraint em JSON-string válida aceita quando correta",async()=>{const pool=memoryPool();pool.state.schema=true;const base=pool.query;pool.query=async(sql,p)=>{const result=await base(sql,p);if(String(sql).includes("FROM pg_constraint")&&p[0]===LEASE_TABLE){result.rows=result.rows.map(r=>r.contype==='u'?{...r,columns:JSON.stringify(r.columns)}:r)}return result};const res=await validateSingleCaseCoordinationSchema(pool);assert.equal(res.ok,true)})

test("índice com colunas em ordem errada é rejeitado",async()=>{const pool=memoryPool();pool.state.schema=true;const base=pool.query;pool.query=async(sql,p)=>{const result=await base(sql,p);if(String(sql).includes("FROM pg_index")){result.rows=result.rows.map(r=>({...r,key_columns:JSON.stringify(["other","expires_at"]) }))}return result};const res=await validateSingleCaseCoordinationSchema(pool);assert.equal(res.ok,false);assert(res.codes.includes("LEASE_EXPIRY_INDEX_MISMATCH"))})

test("CHECK com colunas erradas é rejeitada",async()=>{const pool=memoryPool();pool.state.schema=true;const base=pool.query;pool.query=async(sql,p)=>{const result=await base(sql,p);if(String(sql).includes("FROM pg_constraint")&&p[0]===LEASE_TABLE)result.rows=result.rows.map(r=>r.contype==='c'&&r.conname.includes("lease_token")?{...r,columns:JSON.stringify(["wrong"])}:r);return result};const res=await validateSingleCaseCoordinationSchema(pool);assert.equal(res.ok,false);assert(res.codes.some(c=>c.includes("CHECK_MISMATCH")))})

// Regression tests for PostgreSQL 18 NOT NULL constraints (contype = "n")
test("constraints NOT NULL do PostgreSQL 18 não produzem UNEXPECTED_CONSTRAINT em leases",async()=>{const pool=memoryPool();pool.state.schema=true;const base=pool.query;pool.query=async(sql,p)=>{const result=await base(sql,p);if(String(sql).includes("FROM pg_constraint")&&p[0]===LEASE_TABLE){const notNullConstraints=[{conname:"single_case_apply_leases_acquired_at_not_null",contype:"n",columns:["acquired_at"]},{conname:"single_case_apply_leases_case_import_id_not_null",contype:"n",columns:["case_import_id"]},{conname:"single_case_apply_leases_created_at_not_null",contype:"n",columns:["created_at"]},{conname:"single_case_apply_leases_expires_at_not_null",contype:"n",columns:["expires_at"]},{conname:"single_case_apply_leases_fencing_token_not_null",contype:"n",columns:["fencing_token"]},{conname:"single_case_apply_leases_lease_id_not_null",contype:"n",columns:["lease_id"]},{conname:"single_case_apply_leases_owner_id_not_null",contype:"n",columns:["owner_id"]},{conname:"single_case_apply_leases_updated_at_not_null",contype:"n",columns:["updated_at"]},{conname:"single_case_apply_leases_version_not_null",contype:"n",columns:["version"]}];result.rows=[...result.rows,...notNullConstraints]}return result};const res=await validateSingleCaseCoordinationSchema(pool);assert.equal(res.ok,true);assert.equal(res.codes.length,0)})

test("constraints NOT NULL do PostgreSQL 18 não produzem UNEXPECTED_CONSTRAINT em checkpoints",async()=>{const pool=memoryPool();pool.state.schema=true;const base=pool.query;pool.query=async(sql,p)=>{const result=await base(sql,p);if(String(sql).includes("FROM pg_constraint")&&p[0]===CHECKPOINT_TABLE){const notNullConstraints=[{conname:"single_case_apply_checkpoints_authorizable_plan_hash_not_null",contype:"n",columns:["authorizable_plan_hash"]},{conname:"single_case_apply_checkpoints_authorization_ids_not_null",contype:"n",columns:["authorization_ids"]},{conname:"single_case_apply_checkpoints_case_fingerprint_not_null",contype:"n",columns:["case_fingerprint"]},{conname:"single_case_apply_checkpoints_case_import_id_not_null",contype:"n",columns:["case_import_id"]},{conname:"single_case_apply_checkpoints_case_number_not_null",contype:"n",columns:["case_number"]},{conname:"single_case_apply_checkpoints_checkpoint_payload_not_null",contype:"n",columns:["checkpoint_payload"]},{conname:"single_case_apply_checkpoints_checkpoint_version_not_null",contype:"n",columns:["checkpoint_version"]},{conname:"single_case_apply_checkpoints_created_at_not_null",contype:"n",columns:["created_at"]},{conname:"single_case_apply_checkpoints_fencing_token_not_null",contype:"n",columns:["fencing_token"]},{conname:"single_case_apply_checkpoints_global_status_not_null",contype:"n",columns:["global_status"]},{conname:"single_case_apply_checkpoints_lease_id_not_null",contype:"n",columns:["lease_id"]},{conname:"single_case_apply_checkpoints_schema_version_not_null",contype:"n",columns:["schema_version"]},{conname:"single_case_apply_checkpoints_updated_at_not_null",contype:"n",columns:["updated_at"]}];result.rows=[...result.rows,...notNullConstraints]}return result};const res=await validateSingleCaseCoordinationSchema(pool);assert.equal(res.ok,true);assert.equal(res.codes.length,0)})

test("foreign key inesperada continua produzindo UNEXPECTED_CONSTRAINT",async()=>{const pool=memoryPool();pool.state.schema=true;const base=pool.query;pool.query=async(sql,p)=>{const result=await base(sql,p);if(String(sql).includes("FROM pg_constraint")&&p[0]===LEASE_TABLE){result.rows.push({conname:"unexpected_fk",contype:"f",definition:"FOREIGN KEY (case_import_id) REFERENCES other_table(id)",columns:["case_import_id"]})}return result};const res=await validateSingleCaseCoordinationSchema(pool);assert.equal(res.ok,false);assert(res.codes.some(c=>c.includes("UNEXPECTED_CONSTRAINT")))})

test("exclusion constraint inesperada continua produzindo UNEXPECTED_CONSTRAINT",async()=>{const pool=memoryPool();pool.state.schema=true;const base=pool.query;pool.query=async(sql,p)=>{const result=await base(sql,p);if(String(sql).includes("FROM pg_constraint")&&p[0]===LEASE_TABLE){result.rows.push({conname:"unexpected_exclusion",contype:"x",definition:"EXCLUDE USING gist (case_import_id WITH =)",columns:["case_import_id"]})}return result};const res=await validateSingleCaseCoordinationSchema(pool);assert.equal(res.ok,false);assert(res.codes.some(c=>c.includes("UNEXPECTED_CONSTRAINT")))})

test("nulabilidade divergente continua produzindo erro",async()=>{const pool=memoryPool();pool.state.schema=true;const base=pool.query;pool.query=async(sql,p)=>{const result=await base(sql,p);if(String(sql).includes("information_schema.columns")&&p[0]===LEASE_TABLE){result.rows[0].is_nullable="YES"}return result};const res=await validateSingleCaseCoordinationSchema(pool);assert.equal(res.ok,false);assert(res.codes.some(c=>c.includes("NULLABILITY_MISMATCH")))})


for(const [name,field,value] of [["incremento", "seqincrement","2"],["cycle","seqcycle",true],["tipo","data_type","integer"],["mínimo","seqmin","0"],["máximo","seqmax","999"],["start","seqstart","2"],["cache","seqcache","10"],["ownership","is_owned",true],["objeto homônimo","relkind","r"]])test(`sequência com ${name} divergente é recusada`,async()=>{const pool=memoryPool();pool.state.schema=true;pool.state.sequence[field]=value;const result=await validateSingleCaseCoordinationSchema(pool);assert(result.codes.includes("FENCING_SEQUENCE_MISMATCH"))})
test("sequência integral correta é aceita",async()=>{const pool=memoryPool();pool.state.schema=true;assert.equal((await validateSingleCaseCoordinationSchema(pool)).ok,true)})
test("DDL declara independentemente todas as propriedades da sequência",()=>{assert.match(CREATE_SCHEMA_SQL,/CREATE SEQUENCE IF NOT EXISTS single_case_apply_fencing_token_seq AS BIGINT INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1 NO CYCLE/);assert.deepEqual(SEQUENCE_SPEC,{name:FENCING_SEQUENCE,relkind:"S",dataType:"bigint",increment:"1",minimum:"1",maximum:"9223372036854775807",start:"1",cache:"1",cycle:false,owned:false})})
test("DDL nomeia PK e uniques exigidas pelo catálogo fechado",()=>{for(const name of ["single_case_apply_leases_pkey","single_case_lease_id_unique","single_case_lease_token_unique","single_case_apply_checkpoints_pkey"])assert(CREATE_SCHEMA_SQL.includes(name))})
test("sequência incompatível impede registro e causa rollback",async()=>{const pool=memoryPool();pool.state.schema=true;pool.state.sequence.seqincrement="2";await assert.rejects(()=>migrateSingleCaseCoordination(pool),/SCHEMA_INCOMPATIBLE/);assert.equal(pool.state.migrated,false);assert.equal(pool.state.rollbacks,1)})
for(const [code,expected] of [["ECONNREFUSED","POSTGRES_UNAVAILABLE"],["ECONNRESET","POSTGRES_UNAVAILABLE"],["ETIMEDOUT","POSTGRES_UNAVAILABLE"],["42601","POSTGRES_TRANSACTION_FAILED"]])test(`erro ${code} é sanitizado`,()=>{const source=Object.assign(new Error("secret-host:5432 password=fixture-secret"),{code}),mapped=mapError(source);assert.equal(mapped.message,expected);assert(!mapped.message.includes("secret"))})
test("migração registra somente após validação e é idempotente",async()=>{const pool=memoryPool();assert.equal((await migrateSingleCaseCoordination(pool)).applied,true);assert.equal((await migrateSingleCaseCoordination(pool)).applied,false);assert.equal(pool.state.migrated,true);assert.equal(pool.state.lease,null);assert.equal(pool.state.checkpoint,null)})
test("divergência de schema causa rollback",async()=>{const pool=memoryPool();pool.state.migrated=true;await assert.rejects(()=>migrateSingleCaseCoordination(pool),/SCHEMA_INCOMPATIBLE/);assert.equal(pool.state.rollbacks,1)})
test("composition exige dependências explícitas e não conecta",()=>{const pool=memoryPool();const components=createSingleCaseCoordinationComponents({pool,clock:()=>NOW,ownerId:OWNER,leaseDurationMs:60000});assert(components.coordination);assert.equal(pool.state.writes,0)})
test("CLI permanece fora da composição",()=>{const source=require("node:fs").readFileSync(require.resolve("../src/composition/single-case-coordination-components"),"utf8");assert(!source.includes("apply-single-case"));assert(!source.includes("dotenv"))})

test("sanitização não aceita POSTGRES_ com host e porta",()=>{const source=new Error("POSTGRES_UNAVAILABLE host=db.internal port=5432 token=fake-secret"),mapped=mapError(source);assert.equal(mapped.message,"POSTGRES_TRANSACTION_FAILED");assert(!mapped.message.includes("host"));assert(!mapped.message.includes("port"));assert(!mapped.message.includes("token"))})
test("sanitização não aceita POSTGRES_TRANSACTION_FAILED com SQL",()=>{const source=new Error("POSTGRES_TRANSACTION_FAILED SQL=SELECT * FROM clientes WHERE cpf='00000000000'"),mapped=mapError(source);assert.equal(mapped.message,"POSTGRES_TRANSACTION_FAILED");assert(!mapped.message.includes("SQL"));assert(!mapped.message.includes("SELECT"));assert(!mapped.message.includes("clientes"));assert(!mapped.message.includes("00000000000"))})
test("sanitização não aceita LEASE_OWNER_MISMATCH com pessoa fictícia",()=>{const source=new Error("LEASE_OWNER_MISMATCH owner=Pessoa Fictícia token=fake-secret"),mapped=mapError(source);assert.equal(mapped.message,"POSTGRES_TRANSACTION_FAILED");assert(!mapped.message.includes("owner"));assert(!mapped.message.includes("Pessoa"));assert(!mapped.message.includes("token"))})
test("sanitização não aceita CHECKPOINT_BINDING_MISMATCH com JSON",()=>{const source=new Error('CHECKPOINT_BINDING_MISMATCH checkpoint={"cpf":"00000000000","phone":"11999999999"}'),mapped=mapError(source);assert.equal(mapped.message,"POSTGRES_TRANSACTION_FAILED");assert(!mapped.message.includes("checkpoint"));assert(!mapped.message.includes("cpf"));assert(!mapped.message.includes("00000000000"))})
test("sanitização não aceita SCHEMA_INCOMPATIBLE com comando DDL",()=>{const source=new Error("SCHEMA_INCOMPATIBLE DROP TABLE clientes"),mapped=mapError(source);assert.equal(mapped.message,"POSTGRES_TRANSACTION_FAILED");assert(!mapped.message.includes("DROP"));assert(!mapped.message.includes("TABLE"));assert(!mapped.message.includes("clientes"))})
test("sanitização não aceita LEASE_EXPIRED com sufixo arbitrário",()=>{const source=new Error("LEASE_EXPIRED extra_content"),mapped=mapError(source);assert.equal(mapped.message,"POSTGRES_TRANSACTION_FAILED");assert(!mapped.message.includes("extra"))})
test("sanitização não aceita LEASE_EXPIRED com dois-pontos e sufixo",()=>{const source=new Error("LEASE_EXPIRED: segredo"),mapped=mapError(source);assert.equal(mapped.message,"POSTGRES_TRANSACTION_FAILED");assert(!mapped.message.includes("segredo"))})
test("sanitização não aceita LEASE_EXPIRED com quebra de linha",()=>{const source=new Error("LEASE_EXPIRED\nsegredo-oculto"),mapped=mapError(source);assert.equal(mapped.message,"POSTGRES_TRANSACTION_FAILED");assert(!mapped.message.includes("segredo"));assert(!mapped.message.includes("\n"))})
test("sanitização não aceita prefixo antes do código interno",()=>{const source=new Error("prefixo_LEASE_EXPIRED"),mapped=mapError(source);assert.equal(mapped.message,"POSTGRES_TRANSACTION_FAILED");assert(!mapped.message.includes("prefixo"))})
test("sanitização não aceita FENCING_REJECTED com texto longo e PII",()=>{const source=new Error("FENCING_REJECTED secret-token-abc123def456 " + "x".repeat(100) + " CPF:00000000000 PHONE:11999999999"),mapped=mapError(source);assert.equal(mapped.message,"POSTGRES_TRANSACTION_FAILED");assert(!mapped.message.includes("secret"));assert(!mapped.message.includes("token"));assert(!mapped.message.includes("00000000000"));assert(!mapped.message.includes("11999999999"))})
test("sanitização não aceita INVALID_CHECKPOINT com checkpoint_payload",()=>{const source=new Error("INVALID_CHECKPOINT checkpoint_payload={\"version\":123,\"steps\":{...}}"),mapped=mapError(source);assert.equal(mapped.message,"POSTGRES_TRANSACTION_FAILED");assert(!mapped.message.includes("checkpoint_payload"));assert(!mapped.message.includes("version"))})
test("sanitização não aceita CAS_CONFLICT com detalhes do banco",()=>{const source=new Error("CAS_CONFLICT expected=5 actual=4 table=single_case_apply_checkpoints"),mapped=mapError(source);assert.equal(mapped.message,"POSTGRES_TRANSACTION_FAILED");assert(!mapped.message.includes("expected"));assert(!mapped.message.includes("actual"));assert(!mapped.message.includes("table"))})

test("sanitização preserva LEASE_OWNER_MISMATCH exato",()=>{const source=new Error("LEASE_OWNER_MISMATCH"),mapped=mapError(source);assert.equal(mapped.message,"LEASE_OWNER_MISMATCH");assert(mapped instanceof Error)})
test("sanitização preserva LEASE_ALREADY_HELD exato",()=>{const source=new Error("LEASE_ALREADY_HELD"),mapped=mapError(source);assert.equal(mapped.message,"LEASE_ALREADY_HELD");assert(mapped instanceof Error)})
test("sanitização preserva LEASE_NOT_FOUND exato",()=>{const source=new Error("LEASE_NOT_FOUND"),mapped=mapError(source);assert.equal(mapped.message,"LEASE_NOT_FOUND");assert(mapped instanceof Error)})
test("sanitização preserva LEASE_EXPIRED exato",()=>{const source=new Error("LEASE_EXPIRED"),mapped=mapError(source);assert.equal(mapped.message,"LEASE_EXPIRED");assert(mapped instanceof Error)})
test("sanitização preserva FENCING_REJECTED exato",()=>{const source=new Error("FENCING_REJECTED"),mapped=mapError(source);assert.equal(mapped.message,"FENCING_REJECTED");assert(mapped instanceof Error)})
test("sanitização preserva INVALID_CHECKPOINT exato",()=>{const source=new Error("INVALID_CHECKPOINT"),mapped=mapError(source);assert.equal(mapped.message,"INVALID_CHECKPOINT");assert(mapped instanceof Error)})
test("sanitização preserva CHECKPOINT_BINDING_MISMATCH exato",()=>{const source=new Error("CHECKPOINT_BINDING_MISMATCH"),mapped=mapError(source);assert.equal(mapped.message,"CHECKPOINT_BINDING_MISMATCH");assert(mapped instanceof Error)})
test("sanitização preserva CAS_CONFLICT exato",()=>{const source=new Error("CAS_CONFLICT"),mapped=mapError(source);assert.equal(mapped.message,"CAS_CONFLICT");assert(mapped instanceof Error)})
test("sanitização preserva POSTGRES_UNAVAILABLE exato",()=>{const source=new Error("POSTGRES_UNAVAILABLE"),mapped=mapError(source);assert.equal(mapped.message,"POSTGRES_UNAVAILABLE");assert(mapped instanceof Error)})
test("sanitização preserva POSTGRES_TRANSACTION_FAILED exato",()=>{const source=new Error("POSTGRES_TRANSACTION_FAILED"),mapped=mapError(source);assert.equal(mapped.message,"POSTGRES_TRANSACTION_FAILED");assert(mapped instanceof Error)})
test("sanitização preserva SCHEMA_INCOMPATIBLE exato",()=>{const source=new Error("SCHEMA_INCOMPATIBLE"),mapped=mapError(source);assert.equal(mapped.message,"SCHEMA_INCOMPATIBLE");assert(mapped instanceof Error)})

test("sanitização sempre produz novo Error para código legítimo",()=>{const source=new Error("LEASE_EXPIRED");const mapped=mapError(source);assert.notStrictEqual(mapped,source);assert(mapped instanceof Error);assert.equal(mapped.message,"LEASE_EXPIRED")})
test("sanitização sempre produz novo Error para erro desconhecido",()=>{const source=new Error("UNKNOWN_ERROR_WITH_SECRET_DATA");const mapped=mapError(source);assert.notStrictEqual(mapped,source);assert(mapped instanceof Error);assert.equal(mapped.message,"POSTGRES_TRANSACTION_FAILED");assert(!mapped.message.includes("UNKNOWN"))})
test("sanitização mapeia POOL_UNAVAILABLE para POSTGRES_UNAVAILABLE",()=>{const source=new Error("POOL_UNAVAILABLE");const mapped=mapError(source);assert.equal(mapped.message,"POSTGRES_UNAVAILABLE")})
test("sanitização mapeia código ECONNREFUSED para POSTGRES_UNAVAILABLE",()=>{const source=Object.assign(new Error("connection refused"),{code:"ECONNREFUSED"});const mapped=mapError(source);assert.equal(mapped.message,"POSTGRES_UNAVAILABLE")})
test("sanitização mapeia ConnectionTerminatedError para POSTGRES_UNAVAILABLE",()=>{const source=Object.assign(new Error("connection terminated"),{name:"ConnectionTerminatedError"});const mapped=mapError(source);assert.equal(mapped.message,"POSTGRES_UNAVAILABLE")})

test("sanitização remove completamente stack trace do erro original",()=>{const source=Object.assign(new Error("POSTGRES_UNAVAILABLE secret-connection-string"),{stack:"at secret-place (file.js:123:456)"});const mapped=mapError(source);assert(!mapped.stack||!mapped.stack.includes("secret-place"));assert(!mapped.stack||!mapped.stack.includes("secret-connection"))})
test("sanitização não herda propriedades cause do erro original",()=>{const cause=new Error("ROOT_CAUSE_WITH_SECRETS");const source=Object.assign(new Error("FENCING_REJECTED"),{cause});const mapped=mapError(source);assert(!mapped.cause||!mapped.cause.message.includes("SECRETS"))})
